### ISSUE TITLE
Package description seems wrong ("Todd Atom UI Theme")

### ISSUE THREAD

**Issue by ciarand** [scott-riley/pom#6]
I could be mistaken here, but the package description currently says "Todd Atom UI Theme". Is that intentional? (If it is I'm totally sorry for wasting your time, :disappointed_relieved:).

**Comment by scott-riley** [comment]
Haha, wow, nice work Scott. Todd was Pom's name until I changed it and forgot to take that out the desc. Will fix tonight, thanks!

**Comment by ciarand** [comment]
:+1: I thought something like that might have happened. Love the theme btw!
